[package]
name = "fcm"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
build = "build.rs"

[dependencies]
fcm = { git = "https://github.com/pimeys/fcm-rust" }
amqp = "0.0.16"
protobuf = "1.0.22"
chan-signal = "0.1.6"
argparse = "0.2.1"
env_logger = "0.3.3"
syslog = "3.1.0"
log = "0.3.6"
toml = "0.1.30"
influent = "0.2.2"
histogram = "0.6.1"
rustc-serialize = "0.3.19"
time = "0.1.35"
hyper = "0.9.9"
