[package]
name = "web-push"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
build = "build.rs"

[dependencies]
web-push = { git = "https://github.com/pimeys/rust-web-push" }
tokio-core = "0.1.*"
tokio-signal = "0.1.2"
hyper = { git = "https://github.com/hyperium/hyper" }
protobuf = "1.0.22"
chan-signal = "0.1.6"
argparse = "0.2.1"
env_logger = "0.3.3"
syslog = "3.1.0"
futures = "0.1.*"
log = "0.3.6"
toml = "0.1.30"
rustc-serialize = "0.3.19"
time = "0.1.35"
postgres = "0.11"
r2d2 = "0.7.0"
r2d2_postgres = "0.10.1"
chrono = "0.2"
prometheus = "0.2"
lazy_static = "0.1.*"

[dependencies.amqp]
git = "https://github.com/pimeys/rust-amqp"
branch = "consumer_clean_exit"
default-features = false
