[package]
name = "apns2"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
build = "build.rs"

[dependencies]
apns2 = { git = "https://github.com/pimeys/apns2", branch = "master" }
protobuf = "1.2.1"
chan-signal = "0.1.6"
argparse = "0.2.1"
env_logger = "0.3.3"
syslog = "3.1.0"
log = "0.3.6"
toml = "0.1.30"
rustc-serialize = "0.3.19"
time = "0.1.35"
hyper = "0.9.13"
r2d2 = "0.7.0"
r2d2_postgres = "0.10.1"
prometheus = "0.2"
lazy_static = "0.1.*"

[dependencies.postgres]
version = "0.11"
default-features = true
features = ["time"]

[dependencies.amqp]
git = "https://github.com/pimeys/rust-amqp"
branch = "consumer_clean_exit"
default-features = false
