[package]
name = "web-push"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
build = "build.rs"

[dependencies]
web-push = { git = "https://github.com/pimeys/rust-web-push.git" }
tokio-core = "0.1"
tokio-signal = "0.1"
hyper = "0.11"
protobuf = "1.2"
chan-signal = "0.3"
argparse = "*"
env_logger = "0.5"
gelf = "0.2"
futures = "0.1"
base64 = "0.6"
log = "0.4"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
time = "0.1"
postgres = "0.15"
r2d2 = "0.8"
r2d2_postgres = "0.14"
prometheus = "0.3"
lazy_static = "1.0"

[dependencies.amqp]
git = "https://github.com/pimeys/rust-amqp"
branch = "consumer_clean_exit"
default-features = false
