[package]
name = "fcm"
version = "0.1.0"
authors = ["Julius de Bruijn <julius.debruijn@360dialog.com>"]
build = "build.rs"

[dependencies]
fcm = { git = "https://github.com/panicbit/fcm-rust.git" }
hyper = "0.11"
protobuf = "1.4"
chan-signal = "0.3"
argparse = "0.2"
env_logger = "0.5"
gelf = "0.2"
futures = "0.1"
log = "0.4"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
tokio-core = "0.1"
tokio-signal = "0.1"
time = "0.1"
r2d2 = "0.8"
r2d2_postgres = "0.14"
chrono = "0.4"
prometheus = "0.3"
lazy_static = "1.0"

[dependencies.amqp]
git = "https://github.com/pimeys/rust-amqp"
branch = "consumer_clean_exit"
default-features = false

[dependencies.postgres]
version = "0.15"
default-features = true
features = ["with-time"]