FROM xorc-notifications:latest
MAINTAINER Julius de Bruijn <julius.debruijn@360dialog.com>

RUN mv target/release/web_push /bin
RUN chmod a+x /bin/web_push
RUN rm -rf /usr/src/web_push

ENV CONFIG "/etc/xorc-notifications/web_push.toml"

WORKDIR /

CMD "/bin/web_push"
