[kafka]
input_topic   = "test.notifications.apns"
config_topic  = "test.crm.applications"
output_topic  = "test.oam"
group_id      = "test.consumers.apns"
brokers       = "kafka:9092"
consumer_type = "push_notification"
