[kafka]
input_topic   = "test.notifications.webpush"
config_topic  = "test.crm.applications"
output_topic  = "test.oam"
group_id      = "test.consumers.webpush"
brokers       = "kafka:9092"
consumer_type = "push_notification"
